/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-11-12 22:56:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>LocaCar</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/stylesIndex.css\">\r\n");
      out.write("    <link rel=\"icon\" href=\"imagens/logo site.png\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <nav>\r\n");
      out.write("                <p class=\"brand\">LOCA<strong>CAR</strong></p>\r\n");
      out.write("               \r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li><a href=\"#catalog\">Catálogo</a></li>\r\n");
      out.write("                    <li><a href=\"#about\">Sobre</a></li>\r\n");
      out.write("					\r\n");
      out.write("					<form action=\"login.jsp\" method=\"post\"> \r\n");
      out.write("                    <button type=\"submit\">Login</button>\r\n");
      out.write("                   	</form>\r\n");
      out.write("                    \r\n");
      out.write("                </ul>\r\n");
      out.write("\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div class=\"slide\">\r\n");
      out.write("                <div class=\"header-block\"> \r\n");
      out.write("\r\n");
      out.write("                    <div class=\"text\">\r\n");
      out.write("                        \r\n");
      out.write("                        <h2>O carro perfeito para você</h2>\r\n");
      out.write("    \r\n");
      out.write("                        <P>\r\n");
      out.write("                            \r\n");
      out.write("                        \"Na LocaCar, transformamos cada viagem em uma experiência única sobre rodas.\"\r\n");
      out.write("    \r\n");
      out.write("                        </P>\r\n");
      out.write("    \r\n");
      out.write("                    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("                    <img src=\"imagens/pngegg.png\" alt=\"carro\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <section class=\"catalog\" id=\"catalog\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("           	<div class=\"title-wrapper-catalog\">\r\n");
      out.write("                \r\n");
      out.write("                <h2>Catálogo</h2>\r\n");
      out.write("                <p>Encontre o que você deseja</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"filter-card\">\r\n");
      out.write("\r\n");
      out.write("               	<form action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("	        		<input type=\"text\" class=\"search-input\" name=\"carro\" \r\n");
      out.write("	        		placeholder=\"Escolha seu modelo favorito\">\r\n");
      out.write("	        		<button type=\"submit\" class=\"search-button\">Pesquisar</button>\r\n");
      out.write("        		</form>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!--AQUI COMEÃA A GUIA DOS CARROS -->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card-wrapper\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/1MOBI.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <h3>Fiat Mobi</h3>\r\n");
      out.write("\r\n");
      out.write("						<h5>COMPACTO COM AR</h5>\r\n");
      out.write("						<ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Dir.Hidráulica</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>1 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>5 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        <!-- AQUI MANDA PARA O BACK-END COM O NOME carro E O VALOR carroZaz -->\r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"Mobi\">\r\n");
      out.write("                        <button type=\"submit\">Fiat Mobi</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/2KWID.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("                    \r\n");
      out.write("                        <h3>Renault Kwid</h3>  \r\n");
      out.write("                        \r\n");
      out.write("                        <h5>COMPACTO COM AR</h5>                  \r\n");
      out.write("                        <ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Dir.Hidráulica</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>1 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>5 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"Kwid\">\r\n");
      out.write("                        <button type=\"submit\">Renault Kwid</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/3ZOE.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>Renault Zoe</h3>\r\n");
      out.write("                        \r\n");
      out.write("                        <h5>COMPACTO ELÉTRICO</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Automático</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>1 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>4 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"Zoe\">\r\n");
      out.write("                        <button type=\"submit\">Renault Zoe</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/4GOL.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>Gol</h3>\r\n");
      out.write("                        \r\n");
      out.write("                        <h5>ECONÔMICO COM AR</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Dir.Hidráulica</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>2 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>5 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"Gol\">\r\n");
      out.write("                        <button type=\"submit\">Gol</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/5SANDERO.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>Sandero</h3>\r\n");
      out.write("\r\n");
      out.write("                        <h5>ECONÔMICO COM AR</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Dir.Hidráulica</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>2 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>5 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"Sandero\">\r\n");
      out.write("                        <button type=\"submit\">Sandero</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/6ARGO.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>Argo</h3>\r\n");
      out.write("\r\n");
      out.write("                        <h5>ECONÔMICO ESPECIAL C/AR</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Dir.Hidráulica</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>2 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>5 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"Argo\">\r\n");
      out.write("                        <button type=\"submit\">Argo</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/7HB20.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>HB20</h3>\r\n");
      out.write("\r\n");
      out.write("                        <h5>ECONÔMICO ESPECIAL C/AR</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Dir.Hidráulica</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>2 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>5 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"HB20\">\r\n");
      out.write("                        <button type=\"submit\">HB20</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/8ONIX.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>Onix</h3>\r\n");
      out.write("                 \r\n");
      out.write("                        <h5>ECONÔMICO ESPECIAL C/AR</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Dir.Hidráulica</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>2 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>5 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"Onix\">\r\n");
      out.write("                        <button type=\"submit\">Onix</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-item\">\r\n");
      out.write("\r\n");
      out.write("                    <img src=\"imagens/9C3.png\" alt=\"carro\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"card-content\">\r\n");
      out.write("\r\n");
      out.write("                        <h3>C3</h3>\r\n");
      out.write("\r\n");
      out.write("                        <h5>ECONÔMICO ESPECIAL C/AR</h5>\r\n");
      out.write("                        <ul>\r\n");
      out.write("						\r\n");
      out.write("                        	<li><p>4 portas</p></li>\r\n");
      out.write("							<li><p>Ar condicionado</p></li>\r\n");
      out.write("							<li><p>Vidro elétrico</p></li>\r\n");
      out.write("							<li><p>Trava elétrica</p></li>\r\n");
      out.write("							<li><p>Air bag</p></li>\r\n");
      out.write("							<li><p>Dir.Hidráulica</p></li>\r\n");
      out.write("							<li><p>ABS</p></li>\r\n");
      out.write("							<li><p>2 mala(s) grade(s)</p></li>\r\n");
      out.write("							<li><p>1 mala(s) pequena(s)</p></li>\r\n");
      out.write("							<li><p>5 pessoas</p></li>							\r\n");
      out.write("                        \r\n");
      out.write("                        </ul>\r\n");
      out.write("                        \r\n");
      out.write("                        <form class=\"card-botao\" action=\"selecaoCarros.jsp\" method=\"post\">\r\n");
      out.write("                        <input type=\"hidden\" name=\"carro\" value=\"C3\">\r\n");
      out.write("                        <button type=\"submit\">C3</button>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <section class=\"about\" id=\"about\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"title-wrapper-about\">\r\n");
      out.write("\r\n");
      out.write("                <!--<p>Sobre nÃ³s</p>-->\r\n");
      out.write("                <h3>Sobre</h3>\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"about-content\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"left\">\r\n");
      out.write("                    <img src=\"imagens/logoLocaCar.jpg\" alt=\"About\">\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"right\">\r\n");
      out.write("\r\n");
      out.write("                    <h3>Reuna-se a tecnologia e mobilidade</h3>\r\n");
      out.write("                    <P>\r\n");
      out.write("						A LOCACAR É uma empresa de pequeno porte com a missão de facilitar o \r\n");
      out.write("						aluguel de veículos, oferecendo preços competitivos e um serviço excepcional. \r\n");
      out.write("						Priorizamos a satisfação do cliente, buscando superar suas expectativas e \r\n");
      out.write("						tornar a locação de veículos uma experiência sem complicações.\r\n");
      out.write("						Nossa dedicação à qualidade e ao crescimento contínuo nos impulsiona a \r\n");
      out.write("						servir melhor a cada dia.\r\n");
      out.write("						Conte conosco para suas necessidades de locação de \r\n");
      out.write("						veículos, pois sua satisfação é nossa prioridade.\r\n");
      out.write("                    </P>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("        <div class=\"main\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"content footer-links\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"footer-company\">\r\n");
      out.write("                    \r\n");
      out.write("                    <h4>Empresa</h4>\r\n");
      out.write("\r\n");
      out.write("                    <h6>Sobre</h6>\r\n");
      out.write("\r\n");
      out.write("                    <h6>Contato</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"footer-rental\">\r\n");
      out.write("                    <h4>Aluguel</h4>\r\n");
      out.write("                    <h6>Self-Drive</h6>\r\n");
      out.write("                    <h6>Motorista</h6>\r\n");
      out.write("                    <h6>Ajuda</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"footer-social\">\r\n");
      out.write("\r\n");
      out.write("                    <h4>Permaneça conectado</h4>\r\n");
      out.write("                    <div class=\"social-icons\">\r\n");
      out.write("                    	<a href=\"https://www.instagram.com/henrique_darsh/\">\r\n");
      out.write("                        <img src=\"imagens/instagram.png\" alt=\"Instagram\" >\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <a href=\"https://www.facebook.com/darsh.schneider.3/\">\r\n");
      out.write("                        <img src=\"imagens/facebook-logo.png\" alt=\"Facebook\" >\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"footer-contact\">\r\n");
      out.write("                    <h4>Contato</h4>\r\n");
      out.write("\r\n");
      out.write("                    <h6> 11 977159716</h6>\r\n");
      out.write("                    <h6> henrique.perazzo@hotmail.com</h6>\r\n");
      out.write("                    <h6>Santo Amaro, São Paulo - SP</h6>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"last\"> HP.LoveCraft </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
